name: CI

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi
          pip install pytest
      - name: Run tests
        run: pytest -q

  vendor-integration:
    name: Vendor integration tests (optional)
    runs-on: ubuntu-latest
    if: env.RUN_VENDOR_INTEGRATION == 'true'
    env:
      RUN_VENDOR_INTEGRATION: ${{ env.RUN_VENDOR_INTEGRATION }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install vendor dependencies
        run: |
          python -m pip install --upgrade pip
          # install optional vendor deps if available
          pip install -r vendor/requirements.txt || true
          pip install pytest requests
      - name: Run vendor tests
        run: |
          # These tests require local services; they will be skipped unless services are configured.
          pytest -q vendor/pantheon-server -k "not slow"